version: '3.8'

services:
  # PostgreSQL database
  postgres:
    image: postgres:15
    container_name: library-postgres
    restart: always
    environment:
      POSTGRES_DB: librarydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0609
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    container_name: library-elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  # Kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.3
    container_name: library-kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"

  # Logstash
  logstash:
    image: docker.elastic.co/logstash/logstash:8.11.3
    container_name: library-logstash
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    ports:
      - "5044:5044"   # default beat input port
      - "9600:9600"   # monitoring API
    volumes:
      - ./logstash/config/logstash.conf:/etc/logstash/conf.d/logstash.conf:ro,Z
      - ./logstash/pipeline/spring-app.log:/var/log/spring-app.log:ro,Z
    environment:
      LS_JAVA_OPTS: "-Xms512m -Xmx512m"
    depends_on:
      - elasticsearch

volumes:
  pgdata:
  esdata: